#!/usr/bin/env bash
# Copies the Grafana dashboards and alerting files from the CSMS repo, which
# is their source of truth (the Helm chart copies the same files). Run after
# any dashboard or alert rule change in evtivity-csms-private, then commit.
set -euo pipefail

SRC="${1:-../evtivity-csms-private/prometheus/grafana}"
DEST="$(cd "$(dirname "$0")/.." && pwd)/observability/grafana"

if [ ! -d "$SRC/dashboards" ]; then
  echo "Source not found: $SRC" >&2
  exit 1
fi

mkdir -p "$DEST/dashboards" "$DEST/provisioning/alerting" "$DEST/provisioning/dashboards"
rm -f "$DEST"/dashboards/*.json
cp "$SRC"/dashboards/*.json "$DEST/dashboards/"
# Contact points and datasources are generated by the CDK (SNS topic, AMP
# endpoint), so only the rules, routing policy, and dashboard provider are
# copied. The layout matches /etc/grafana/provisioning in the container.
cp "$SRC/provisioning/alerting/rules.yml" "$SRC/provisioning/alerting/policies.yml" "$DEST/provisioning/alerting/"
cp "$SRC/provisioning/dashboards/dashboards.yml" "$DEST/provisioning/dashboards/"
echo "Synced from $SRC"
