#!/usr/bin/env bash
# Copies the Grafana dashboards and alerting files from the CSMS repo, which
# is their source of truth (the Helm chart copies the same files). Run after
# any dashboard or alert rule change in the CSMS repo, then commit.
#
# Usage: scripts/sync-observability.sh <path to the CSMS repo>/prometheus/grafana
set -euo pipefail

if [ $# -ne 1 ]; then
  sed -n 6p "$0" | sed 's/^# //' >&2
  exit 1
fi
SRC="$1"
DEST="$(cd "$(dirname "$0")/.." && pwd)/observability/grafana"

if [ ! -d "$SRC/dashboards" ]; then
  echo "Source not found: $SRC" >&2
  exit 1
fi

mkdir -p "$DEST/dashboards" "$DEST/provisioning/alerting" "$DEST/provisioning/dashboards"
rm -f "$DEST"/dashboards/*.json
# The logs dashboard is generated by the CDK for CloudWatch Logs. The Helm
# chart's version queries Loki, which this stack does not run.
for f in "$SRC"/dashboards/*.json; do
  [ "$(basename "$f")" = logs.json ] || cp "$f" "$DEST/dashboards/"
done
# Contact points and datasources are generated by the CDK (SNS topic, AMP
# endpoint), so only the rules, routing policy, and dashboard provider are
# copied. The layout matches /etc/grafana/provisioning in the container.
cp "$SRC/provisioning/alerting/rules.yml" "$SRC/provisioning/alerting/policies.yml" "$DEST/provisioning/alerting/"
cp "$SRC/provisioning/dashboards/dashboards.yml" "$DEST/provisioning/dashboards/"
echo "Synced from $SRC"
